### ISSUE TITLE
Installation fails with error because the | test operator is deprecated in Ansible 2.5

### ISSUE THREAD

**Issue by Snadex** [cscart/server-ansible-playbooks#20]
Hello,
using the playbook inventory_varnish lvemp7.yml results in errors due to deprecated test operator.

Explanation and solution here:
https://forum.cs-cart.com/topic/56857-installation-playbook-fails/

**Comment by andytheapedemontague** [comment]
@Snadex I have a [branch that works on Ansible 2.9](https://github.com/andytheapedemontague/server-ansible-playbooks/tree/ansible-2.9) now so if you want to help test the fix, feel free to give it a go

**Comment by torunar** [comment]
Merged.
