### ISSUE TITLE
Facing issue when running the ansible script for Ubuntu 18.04

### ISSUE THREAD

**Issue by tabkad12** [cscart/server-ansible-playbooks#32]
TASK [mysql/common : checking for previous installation] ****************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [mysql/common : preseeding MySQL file] *****************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [mysql/common : command] *******************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [mysql/common : Add Mysql apt key.] ********************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key adv --keyserver ha.pool.sks-keyservers.net --recv A4A9406876FCBD3C456770C88C718D3B5072E1F5", "msg": "Error fetching key A4A9406876FCBD3C456770C88C718D3B5072E1F5 from keyserver: ha.pool.sks-keyservers.net", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No name\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: keyserver receive failed: No name"], "stdout": "Executing: /tmp/apt-key-gpghome.1xhTFKOwwX/gpg.1.sh --keyserver ha.pool.sks-keyservers.net --recv A4A9406876FCBD3C456770C88C718D3B5072E1F5\n", "stdout_lines": ["Executing: /tmp/apt-key-gpghome.1xhTFKOwwX/gpg.1.sh --keyserver ha.pool.sks-keyservers.net --recv A4A9406876FCBD3C456770C88C718D3B5072E1F5"]}
	to retry, use: --limit @/root/playbooks/lemp74.retry

PLAY RECAP **************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=100  changed=20   unreachable=0    failed=1

**Comment by tabkad12** [comment]
Any help or guidance to resolve the above stated will be highly appreciated.

**Comment by defremov-cscart** [comment]
Fixed in https://github.com/cscart/server-ansible-playbooks/commit/5d77bf6d54c26b8c15d7c78bfe381e61a7150e19
Previous keyserver "This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.
Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all."

**Comment by tabkad12** [comment]
It is working now. Thanks for your swift action.
