### ISSUE TITLE
unable to access 'https://github.com/cscart/server-ansible-playbooks/': Peer reports incompatible or unsupported protocol version.

### ISSUE THREAD

**Issue by serg-avens** [cscart/server-ansible-playbooks#36]
Решил такое сообщение в чистой CentOS 7
На шаге 2.1 такая ошибка unable to access 'https://github.com/cscart/server-ansible-playbooks/': Peer reports incompatible or unsupported protocol version.
Решение:  sudo yum update -y nss curl libcurl

Еще такая ошибка:  при yum install  пишет: Cannot retrieve metalink for repository: epel/x86_64. 
Решение:   --disablerepo=epel

А вот шаг 3 запуск плейбука победить не удалось.
TASK [php7/common : installing repository to CentOS 7] ******************************************************************************************************
failed: [127.0.0.1] (item=[u'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', u'https://mirror.webtatic.com/yum/el7/webtatic-release.rpm']) => {"changed": false, "failed": true, "item": ["https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm", "https://mirror.webtatic.com/yum/el7/webtatic-release.rpm"], "msg": "Failed to validate the SSL certificate for mirror.webtatic.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.5 (default, Jun 17 2014, 18:11:42) [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure."}

**Comment by defremov-cscart** [comment]
Проверил на чистой `CentOS Linux release 7.8.2003 (Core)`
`127.0.0.1                  : ok=129  changed=67   unreachable=0    failed=0`
